"""initial_schema

Revision ID: 6fd0fe19a093
Revises: 
Create Date: 2026-08-25 13:37:16.410278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
try:
    import pgvector
    from pgvector.sqlalchemy import Vector
except ImportError:
    Vector = sa.JSON


# revision identifiers, used by Alembic.
revision: str = '6fd0fe19a093'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('readiness_boost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_skill_name'), 'assessments', ['skill_name'], unique=False)
    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('monthly_orders', sa.Integer(), nullable=True),
    sa.Column('current_tech', sa.JSON(), nullable=True),
    sa.Column('challenges', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_business_type'), 'business_profiles', ['business_type'], unique=False)
    op.create_table('business_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('expected_benefit', sa.Text(), nullable=False),
    sa.Column('effort', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('cost_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_recommendations_category'), 'business_recommendations', ['category'], unique=False)
    op.create_table('careers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('education_expectations', sa.Text(), nullable=True),
    sa.Column('typical_experience', sa.String(length=100), nullable=True),
    sa.Column('prep_effort_months', sa.String(length=100), nullable=True),
    sa.Column('opportunity_demand', sa.String(length=50), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_category'), 'careers', ['category'], unique=False)
    op.create_index(op.f('ix_careers_title'), 'careers', ['title'], unique=True)
    op.create_table('government_recruitments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruiting_body', sa.String(length=100), nullable=False),
    sa.Column('recruitment_name', sa.String(length=255), nullable=False),
    sa.Column('notification_number', sa.String(length=100), nullable=True),
    sa.Column('notification_url', sa.String(length=512), nullable=True),
    sa.Column('official_apply_url', sa.String(length=512), nullable=True),
    sa.Column('application_start_date', sa.DateTime(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('exam_dates', sa.String(length=255), nullable=True),
    sa.Column('total_vacancies', sa.Integer(), nullable=True),
    sa.Column('selection_process', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_recruitments_recruiting_body'), 'government_recruitments', ['recruiting_body'], unique=False)
    op.create_table('learning_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('practical_task', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_skill_name'), 'learning_resources', ['skill_name'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessment_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('career_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('is_required', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digital_maturity_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('digital_maturity_score', sa.Float(), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('career_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('experience_min', sa.Float(), nullable=True),
    sa.Column('experience_max', sa.Float(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_category'), 'opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_opportunities_source_external_id'), 'opportunities', ['source_external_id'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_skills', sa.JSON(), nullable=True),
    sa.Column('parsed_education', sa.String(length=255), nullable=True),
    sa.Column('parsed_experience_years', sa.Float(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias'), 'skill_aliases', ['alias'], unique=True)
    op.create_table('skill_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_skill_id', sa.String(length=36), nullable=False),
    sa.Column('child_skill_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['child_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_assessment_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('passed', sa.String(length=20), nullable=True),
    sa.Column('readiness_boost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assessment_results_user_id'), 'user_assessment_results', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('career_goal', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('work_preference', sa.String(length=50), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('verified', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skills_skill_name'), 'user_skills', ['skill_name'], unique=False)
    op.create_table('government_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recruitment_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('post_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('pay_level', sa.String(length=50), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=True),
    sa.Column('education_required', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('experience_years_required', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['recruitment_id'], ['government_recruitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('is_required', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('government_eligibility_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('age_relaxation_years', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Integer(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['government_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('government_eligibility_rules')
    op.drop_table('opportunity_skills')
    op.drop_table('government_posts')
    op.drop_index(op.f('ix_user_skills_skill_name'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_assessment_results_user_id'), table_name='user_assessment_results')
    op.drop_table('user_assessment_results')
    op.drop_table('skill_relationships')
    op.drop_index(op.f('ix_skill_aliases_alias'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_external_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('digital_maturity_assessments')
    op.drop_table('career_skills')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_learning_resources_skill_name'), table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_government_recruitments_recruiting_body'), table_name='government_recruitments')
    op.drop_table('government_recruitments')
    op.drop_index(op.f('ix_careers_title'), table_name='careers')
    op.drop_index(op.f('ix_careers_category'), table_name='careers')
    op.drop_table('careers')
    op.drop_index(op.f('ix_business_recommendations_category'), table_name='business_recommendations')
    op.drop_table('business_recommendations')
    op.drop_index(op.f('ix_business_profiles_business_type'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_assessments_skill_name'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
